Rails.application.config.assets.precompile += %w( homes.css )
Rails.application.config.assets.precompile += %w( homes.js )
Rails.application.config.assets.precompile += %w( projects.css )
Rails.application.config.assets.precompile += %w( projects.js )
Rails.application.config.assets.precompile += %w( questions.css )
Rails.application.config.assets.precompile += %w( questions.js )
Rails.application.config.assets.precompile += %w( microsites.css )
Rails.application.config.assets.precompile += %w( microsites.js )